In [14]:
import pandas as pd
from math import radians
import numpy as np
import matplotlib
matplotlib.use('TkAgg')
from IPython.display import display
import matplotlib as mpl
from matplotlib import cm

In [3]:
import matplotlib.pyplot as plt
# import for 3d plot
from mpl_toolkits.mplot3d import Axes3D

In [4]:
path='DrillHole3d/data/Trek_North_Zone_DDH_Database_Master.xlsx'
file=pd. ExcelFile('DrillHole3d/data/Trek_North_Zone_DDH_Database_Master.xlsx')

In [5]:
file.sheet_names

['TrekDDH',
 'LookupTables',
 'Collars',
 'Survey',
 'Assays MapInfo',
 'Litho',
 'Alteration',
 'Mineralization',
 'Recovery',
 '01',
 '02',
 '03',
 '04',
 '05',
 '06',
 '07',
 '08',
 '09',
 'Strater',
 'SummarybyHole',
 'AssaySummaries',
 'Assay Pivots',
 'Core Library',
 'Petrography Submit']

In [6]:
survey=pd.read_excel('DrillHole3d/data/Trek_North_Zone_DDH_Database_Master.xlsx',sheet_name='Survey')
collar=pd.read_excel('DrillHole3d/data/Trek_North_Zone_DDH_Database_Master.xlsx',sheet_name='Collars')
lith=pd.read_excel('DrillHole3d/data/Trek_North_Zone_DDH_Database_Master.xlsx',sheet_name='Assays MapInfo')

In [7]:
collar

     Hole ID  Easting  Northing  Elevation  Azimuth   Dip  Total Depth
0   TRK08-01   360792   6326535       1280    245.0 -70.0    196.59600
1   TRK08-02   360792   6326535       1280    360.0 -90.0    321.25920
2   TRK08-03   360792   6326535       1280     65.0 -70.0    209.48904
3   TRK08-04   360857   6326422       1227    257.0 -80.0    173.73600
4   TRK08-05   360857   6326422       1227     77.0 -70.0    311.50560
5   TRK08-06   360739   6326634       1326    130.0 -90.0    195.98640
6   TRK09-01   360906   6326525       1296    340.4 -77.1    321.00000
7   TRK09-02   361232   6326792       1536    166.6 -79.6    150.00000
8   TRK09-03   361157   6326653       1445    287.7 -67.1    174.00000
9   TRK09-04   361232   6326792       1536    251.8 -70.1    141.00000
10  TRK09-05   360995   6326545       1310    350.5 -81.9    399.00000
11  TRK09-06   360878   6326481       1246    321.8 -64.6    309.00000
12  TRK09-07   360779   6326503       1245    256.9 -52.3    201.00000
13  TRK09-08   360648   6326374       1091    357.3 -45.1    240.00000
14  TRK09-09   360998   6326654       1378    353.3 -82.4    435.00000

In [8]:
survey.head(5)

    Hole ID   Depth_m  Azimuth   Dip
0  TRK08-01    0.0000    250.0 -70.0
1  TRK08-01  152.0952    241.0 -69.3
2  TRK08-02    0.0000      0.0 -88.2
3  TRK08-02  182.8800    254.4 -88.2
4  TRK08-02  243.8400    269.9 -88.2

In [9]:
lith

,Hole ID,From_m,To_m,Sample ID,Cu_%,Au_ppm,Ag_ppm,Al_%,As_ppm,B_ppm,...,Tl_ppm,U_ppm,V_ppm,W_ppm,Zn_ppm,Cu_%.1,Pb_%,Ag_%,Zn_%,Au_%
0,TRK08-01,2.1336,2.7432,G0806743,0.0053,0.016,-1,1.16,12.0,-1.0,...,-1.0,-1.0,107.0,-1.0,25,NaN,NaN,NaN,NaN,0.016
1,TRK08-01,2.7432,4.2672,G0806744,0.0064,0.023,-1,1.21,14.0,-1.0,...,-1.0,-1.0,124.0,-1.0,10,NaN,NaN,NaN,NaN,0.023
2,TRK08-01,4.2672,5.7912,G0806745,0.0122,0.034,-1,1.05,16.0,-1.0,...,-1.0,-1.0,119.0,-1.0,15,NaN,NaN,NaN,NaN,0.034
3,TRK08-01,5.7912,7.3152,G0806746,0.0111,0.028,0.3,1.30,13.0,-1.0,...,-1.0,-1.0,99.0,-1.0,90,NaN,NaN,NaN,NaN,0.028
4,TRK08-01,7.3152,8.8392,G0806747,0.0124,0.03,0.2,1.14,16.0,10.0,...,-1.0,-1.0,100.0,-1.0,35,NaN,NaN,NaN,NaN,0.030
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1966,TRK09-09,422.0000,424.0000,H138775,0.3090,0.295,4.3,1.81,10.0,-1.0,...,-1.0,-1.0,117.0,-1.0,75,NaN,NaN,NaN,0.0,0.295
1967,TRK09-09,424.0000,426.0000,H138776,0.1440,0.196,2.6,1.56,6.0,10.0,...,-1.0,-1.0,162.0,-1.0,89,NaN,NaN,NaN,0.0,0.196
1968,TRK09-09,426.0000,429.0000,H138777,0.0952,0.069,1.4,1.55,4.0,10.0,...,-1.0,-1.0,88.0,-1.0,57,NaN,NaN,NaN,0.0,0.069
1969,TRK09-09,429.0000,432.0000,H138778,0.0565,0.1,1.1,1.25,6.0,10.0,...,-1.0,-1.0,104.0,-1.0,48,NaN,NaN,NaN,0.0,0.100
1970,TRK09-09,432.0000,435.0000,H138780,0.0372,0.049,0.9,1.23,-1.0,60.0,...,-1.0,-1.0,87.0,-1.0,64,NaN,NaN,NaN,0.0,0.049

In [10]:
## grab start location information
collars_collar_col='Hole ID'
x_col='Easting' 
y_col='Northing'
z_col='Elevation'


## grab survey columns will be user choice
survey_collar_col='Hole ID'
dip_col='Dip'
azi_col='Azimuth'
survey_depth_col='Depth_m'

### grab the data depth
data_collar_col='Hole ID'
data_z_col1='From_m'
data_z_col2='To_m'
fig = plt.figure()
ax = fig.add_subplot(111, projection = '3d')

In [24]:
cmaps = {}

gradient = np.linspace(0, 1, 256)
gradient = np.vstack((gradient, gradient))


def plot_color_gradients(category, cmap_list):
    # Create figure and adjust figure height to number of colormaps
    nrows = len(cmap_list)
    figh = 0.35 + 0.15 + (nrows + (nrows - 1) * 0.1) * 0.22
    fig, axs = plt.subplots(nrows=nrows + 1, figsize=(6.4, figh))
    fig.subplots_adjust(top=1 - 0.35 / figh, bottom=0.15 / figh,
                        left=0.2, right=0.99)
    axs[0].set_title(f'{category} colormaps', fontsize=14)

    for ax, name in zip(axs, cmap_list):
        ax.imshow(gradient, aspect='auto', cmap=mpl.colormaps[name])
        ax.text(-0.01, 0.5, name, va='center', ha='right', fontsize=10,
                transform=ax.transAxes)

    # Turn off *all* ticks & spines, not just the ones with colormaps.
    for ax in axs:
        ax.set_axis_off()

    # Save colormap list for later.
    cmaps[category] = cmap_list
    fig.show()

In [25]:
plot_color_gradients('Suggested Color Map options',
                     ['gist_earth','hsv','brg', 'gist_rainbow', 'rainbow', 'jet',
                      'turbo', 'nipy_spectral', 'gist_ncar', 'hsv'])

2023-03-08 09:12:06.669 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:09.059 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:09.069 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:09.081 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:09.088 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:09.102 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:09.136 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:09.154 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:09.170 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:09.186 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:09.202 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:09.219 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:09.236 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:09.253 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:09.269 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:09.322 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:34.979 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:35.081 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:35.193 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:35.295 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:35.411 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:35.521 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:35.624 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:35.733 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:35.839 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:35.991 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:36.099 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:36.204 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:36.306 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:37.407 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:38.415 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:38.907 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:39.016 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:39.116 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:39.311 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:39.498 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:39.608 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:39.729 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:39.839 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:39.998 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:40.111 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:40.229 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:40.339 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:40.462 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:40.580 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:40.690 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:12:40.813 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:13:12.922 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:13:15.674 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:13:15.940 python[2272:20827] +[CATransaction synchronize] called within transaction
2023-03-08 09:13:19.456 python[2272:20827] +[CATransaction synchronize] called within transaction

In [26]:
plot_color_gradients('Perceptually Uniform Sequential',
                     ['viridis', 'plasma', 'inferno', 'magma', 'cividis'])

2023-03-08 09:13:49.176 python[2272:20827] +[CATransaction synchronize] called within transaction

In [27]:
plot_color_gradients('Sequential',
                     ['Greys', 'Purples', 'Blues', 'Greens', 'Oranges', 'Reds',
                      'YlOrBr', 'YlOrRd', 'OrRd', 'PuRd', 'RdPu', 'BuPu',
                      'GnBu', 'PuBu', 'YlGnBu', 'PuBuGn', 'BuGn', 'YlGn'])

2023-03-08 09:14:09.089 python[2272:20827] +[CATransaction synchronize] called within transaction

In [28]:
plot_color_gradients('Sequential (2)',
                     ['binary', 'gist_yarg', 'gist_gray', 'gray', 'bone',
                      'pink', 'spring', 'summer', 'autumn', 'winter', 'cool',
                      'Wistia', 'hot', 'afmhot', 'gist_heat', 'copper'])

2023-03-08 09:14:25.127 python[2272:20827] +[CATransaction synchronize] called within transaction

In [29]:
plot_color_gradients('Diverging',
                     ['PiYG', 'PRGn', 'BrBG', 'PuOr', 'RdGy', 'RdBu', 'RdYlBu',
                      'RdYlGn', 'Spectral', 'coolwarm', 'bwr', 'seismic'])

2023-03-08 09:14:40.133 python[2272:20827] +[CATransaction synchronize] called within transaction

In [10]:
def calc_xyz(azi,dip,depth):
    # scalar length be is the distance from the previous point or depth in geo terms

    x_hat = depth*np.cos(dip)*np.sin(azi)
    y_hat = depth*np.cos(dip)*np.cos(azi) 
    z_hat = depth*np.sin(dip) 
    return x_hat,y_hat,z_hat

In [11]:
import matplotlib as mpl
from matplotlib import cm
class MplColorHelper:

  def __init__(self, cmap_name, start_val, stop_val):
    self.cmap_name = cmap_name
    self.cmap = plt.get_cmap(cmap_name)
    self.norm = mpl.colors.Normalize(vmin=start_val, vmax=stop_val)
    self.scalarMap = cm.ScalarMappable(norm=self.norm, cmap=self.cmap)


  def get_rgb(self, val):
    return self.scalarMap.to_rgba(val)

In [12]:
cmap=MplColorHelper(cmap_name='coolwarm',start_val=0,stop_val=1)

In [19]:
drill_data=[]
for name,group in lith.groupby('Hole ID'):
    surv=survey[survey[survey_collar_col]==name]
    start_data=collar[collar[collars_collar_col]==name]
    for i in surv[survey_depth_col].values:
        group.loc[-1,data_z_col1]=i
        group=group.reset_index(drop=True)

    group=group.sort_values(data_z_col1)
    data=pd.merge(group,surv,left_on=[data_z_col1],right_on=[survey_depth_col],how = 'left',
                                                                                suffixes=('', '_delme')  # Left gets no suffix, right gets something identifiable
                                                                                )
    # data = data[[c for c in data.columns if not c.endswith('_delme')]]
    data[[azi_col,dip_col]]=data[[azi_col,dip_col]].fillna(method='ffill').fillna(method='bfill')
    drop=data[data[data_collar_col].isna()].index
    data=data.drop(drop).fillna(0).reset_index(drop=True)
    
    ## convert angles to radians
    data [azi_col]=data [azi_col].apply(radians)
    data [dip_col]=data [dip_col].apply(radians)

    ## grab starting coordinates
    start_x=start_data[x_col].values[0]
    start_y=start_data[y_col].values[0]
    start_z=start_data[z_col].values[0]
    print('Starting xyz',start_x,start_y,start_z)
    # display(data)

    # grab starting depth
    last_depth=data.loc[0,data_z_col1]

    data.loc[0,x_col]=start_x
    data.loc[0,y_col]=start_y
    data.loc[0,z_col]=start_z

    ax.scatter(start_x,start_y,start_z)
    # display(data)
    
    for i, row in data.iterrows():
        if i>0:
            new_depth=row[data_z_col1]

            azi=row[azi_col]
            dip=row[dip_col]

            distance=np.abs(new_depth-last_depth)

        
            x_hat,y_hat,z_hat=calc_xyz(azi=azi,dip=dip,depth=distance)


            x=start_x+x_hat
            y=start_y+y_hat
            z=start_z+z_hat

            data.loc[i,x_col]=x
            data.loc[i,y_col]=y
            data.loc[i,z_col]=z
            
            start_x=x
            start_y=y
            start_z=z

            last_depth=new_depth

    ax.plot(data[x_col],data[y_col],data[z_col])
    # display(data.columns)
    drill_data.append(data)
drill_holes=pd.concat(drill_data,axis=0)
drill_holes.columns

Starting xyz 360792 6326535 1280
Starting xyz 360792 6326535 1280
Starting xyz 360792 6326535 1280
Starting xyz 360857 6326422 1227
Starting xyz 360857 6326422 1227
Starting xyz 360739 6326634 1326
Starting xyz 360906 6326525 1296
Starting xyz 361232 6326792 1536
Starting xyz 361157 6326653 1445
Starting xyz 361232 6326792 1536
Starting xyz 360995 6326545 1310
Starting xyz 360878 6326481 1246
Starting xyz 360779 6326503 1245
Starting xyz 360648 6326374 1091
Starting xyz 360998 6326654 1378

Index(['Hole ID', 'From_m', 'To_m', 'Sample ID', 'Cu_%', 'Au_ppm', 'Ag_ppm',
       'Al_%', 'As_ppm', 'B_ppm', 'Ba_ppm', 'Be_ppm', 'Bi_ppm', 'Ca_%',
       'Cd_ppm', 'Co_ppm', 'Cr_ppm', 'Cu_ppm', 'Fe_%', 'Ga_ppm', 'Hg_ppm',
       'K_%', 'La_ppm', 'Mg_%', 'Mn_ppm', 'Mo_ppm', 'Na_%', 'Ni_ppm', 'P_ppm',
       'Pb_ppm', 'S_%', 'Sb_ppm', 'Sc_ppm', 'Sr_ppm', 'Th_ppm', 'Ti_%',
       'Tl_ppm', 'U_ppm', 'V_ppm', 'W_ppm', 'Zn_ppm', 'Cu_%.1', 'Pb_%', 'Ag_%',
       'Zn_%', 'Au_%', 'Hole ID_delme', 'Depth_m', 'Azimuth', 'Dip', 'Easting',
       'Northing', 'Elevation'],
      dtype='object')

In [ ]:
fig.show()

In [29]:
from importlib.metadata import version
import subprocess
import sys
xl=version('openpyxl')
xl.split('.')
vers=xl.split('.')
if int(vers[1])==0 and int(vers[0])==3:
    print(xl,'wrong version')
    print('wrong version')

def check_xl_version():
    xl=version('openpyxl')
    xl.split('.')
    vers=xl.split('.')
    if int(vers[1])==0 and int(vers[0])==3:
        print(xl,'wrong version')
        subprocess.call([sys.executable, '-m', 'pip', 'install', '--force-reinstall','-v', "openpyxl==3.1.0"])

3.0.10 wrong version
wrong version

In [ ]:
mpl.colors.CenteredNorm(,)